import {
  AtSign,
  Bell,
  BellOff,
  Bold,
  Bookmark,
  Bot,
  Blocks,
  Camera,
  Check,
  CheckSquare,
  Code2,
  ChevronLeft,
  ChevronRight,
  CircleUserRound,
  Clock,
  ContactRound,
  Copy,
  Database,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  SmilePlus,
  Flag,
  Filter,
  Folder,
  Heart,
  Heading,
  House,
  Image,
  Italic,
  Link2,
  List,
  LogOut,
  Maximize2,
  Mic,
  Minimize2,
  Megaphone,
  Menu,
  MessageCircle,
  Minus,
  MonitorSmartphone,
  Moon,
  MoreHorizontal,
  Phone,
  PanelRightOpen,
  Pin,
  Share2,
  Plus,
  Quote,
  RotateCcw,
  Orbit,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Signal,
  Sparkles,
  Star,
  Sun,
  ThumbsUp,
  Trash2,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  Volume2,
  VolumeX,
  X,
  type LucideIcon
} from 'lucide-react';

const icons = {
  message: MessageCircle,
  feed: Orbit,
  users: Users,
  contacts: ContactRound,
  bell: Bell,
  bellOff: BellOff,
  profile: User,
  send: Send,
  plus: Plus,
  search: Search,
  close: X,
  minus: Minus,
  maximize: Maximize2,
  shrink: Minimize2,
  settings: Settings,
  logout: LogOut,
  sun: Sun,
  moon: Moon,
  phone: Phone,
  mobileMode: PanelRightOpen,
  pin: Pin,
  share: Share2,
  video: Video,
  more: MoreHorizontal,
  image: Image,
  camera: Camera,
  folder: Folder,
  clock: Clock,
  emoji: SmilePlus,
  upload: Upload,
  trash: Trash2,
  filter: Filter,
  menu: Menu,
  chevronLeft: ChevronLeft,
  chevron: ChevronRight,
  ccw: CircleUserRound,
  check: Check,
  checkSquare: CheckSquare,
  copy: Copy,
  database: Database,
  edit: Edit3,
  eye: Eye,
  eyeOff: EyeOff,
  flag: Flag,
  heart: Heart,
  like: ThumbsUp,
  recall: RotateCcw,
  quote: Quote,
  shield: Shield,
  shieldCheck: ShieldCheck,
  signal: Signal,
  sparkles: Sparkles,
  star: Star,
  bookmark: Bookmark,
  bot: Bot,
  blocks: Blocks,
  code: Code2,
  external: ExternalLink,
  device: MonitorSmartphone,
  userPlus: UserPlus,
  muted: VolumeX,
  volume: Volume2,
  announcement: Megaphone,
  mic: Mic,
  atSign: AtSign,
  bold: Bold,
  italic: Italic,
  heading: Heading,
  home: House,
  list: List,
  link: Link2
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

interface IconProps {
  name: IconName;
  className?: string;
}

export function Icon({ name, className = 'h-5 w-5' }: IconProps): JSX.Element {
  const LucideIconComponent = icons[name];
  return <LucideIconComponent className={className} strokeWidth={1.9} aria-hidden="true" />;
}
